# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgUKbJ_M4bQd4WkxzzGT_2sG1xalmyuW
"""

import random

N = 6
personas = list(range(N))


satisfaction = [[random.randint(0, 10) if i != j else 0 for j in range(N)] for i in range(N)]

def evaluar(asientos):
    total = 0
    for i in range(N):
        izquierda = asientos[i - 1]
        derecha = asientos[(i + 1) % N]
        persona = asientos[i]
        total += satisfaction[persona][izquierda] + satisfaction[persona][derecha]
    return total

def hill_climbing(iteraciones=1000):
    actual = personas[:]
    random.shuffle(actual)
    mejor_eval = evaluar(actual)

    for _ in range(iteraciones):
        vecino = actual[:]
        i, j = random.sample(range(N), 2)
        vecino[i], vecino[j] = vecino[j], vecino[i]

        eval_vecino = evaluar(vecino)

        if eval_vecino > mejor_eval:
            actual = vecino
            mejor_eval = eval_vecino

    return actual, mejor_eval

#
mejor_disposicion, mejor_valor = hill_climbing(2000)

print("Matriz de satisfacción (0-10):")
for fila in satisfaction:
    print(fila)
print("\nMejor disposición encontrada:", mejor_disposicion)
print("Satisfacción total:", mejor_valor)