# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEhfSUbRsDbtqjyAUt85qfsKN_SGGIJ9
"""

def cambio_voraz(monto, monedas):
    monedas.sort(reverse=True)  # Ordenar de mayor a menor
    resultado = []

    for moneda in monedas:
        while monto >= moneda:
            monto -= moneda
            resultado.append(moneda)

    return resultado

monto = 63
monedas = [50, 20, 10, 5, 1]

resultado = cambio_voraz(monto, monedas)

print(f"Monto a cambiar: ${monto}")
print("Monedas disponibles:", monedas)
print("Monedas seleccionadas:", resultado)
print(f"Total de monedas usadas: {len(resultado)}")