# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHsw8ACiXkCs925vVge89f251aoC9bQd
"""

import random

jugadas = ["piedra", "papel", "tijera"]

def resultado(jugador, oponente):
    if jugador == oponente:
        return "empate"
    elif (jugador == "piedra" and oponente == "tijera") or \
         (jugador == "papel" and oponente == "piedra") or \
         (jugador == "tijera" and oponente == "papel"):
        return "gana"
    else:
        return "pierde"

def estrategia_voraz(historial):
    if not historial:
        return random.choice(jugadas)
    ultima_jugada = historial[-1][0]
    resultado_ultimo = historial[-1][2]
    if resultado_ultimo == "gana":
        return ultima_jugada
    elif resultado_ultimo == "pierde":
        ultima_oponente = historial[-1][1]
        if ultima_oponente == "piedra":
            return "papel"
        elif ultima_oponente == "papel":
            return "tijera"
        else:
            return "piedra"
    else:
        return random.choice(jugadas)

def estrategia_racional(jugada_voraz):
    if jugada_voraz == "piedra":
        return "papel"
    elif jugada_voraz == "papel":
        return "tijera"
    else:
        return "piedra"

historial = []
rondas = 10

for ronda in range(rondas):
    jugada_jugador = estrategia_voraz(historial)
    jugada_oponente = estrategia_racional(jugada_jugador)
    res = resultado(jugada_jugador, jugada_oponente)
    historial.append((jugada_jugador, jugada_oponente, res))
    print(f"Ronda {ronda+1}: Jugador → {jugada_jugador}, Oponente → {jugada_oponente} → {res}")

ganadas = sum(1 for _, _, r in historial if r == "gana")
perdidas = sum(1 for _, _, r in historial if r == "pierde")
empates = sum(1 for _, _, r in historial if r == "empate")

print("\nResumen final:")
print(f"Ganadas: {ganadas}, Perdidas: {perdidas}, Empates: {empates}")